-- Конфигурационные справочники интерфейса SVAP Query Service.

INSERT INTO dictionaries_cache (business, dictionary_code, item_code, item_short_name, item_full_name, analytical_attribute_code)
VALUES
    ('FB', 'SVAP_QUERY_TYPES', 'FSG', 'FSG', 'Расчет состояния счетов учета за период', NULL),
    ('FB', 'SVAP_QUERY_TYPES', 'TURN', 'TURN', 'Расчет оборотов по счетам учета в разрезе документов', NULL),
    ('FB', 'SVAP_QUERY_TYPES', 'COR', 'COR', 'Расчет оборотов в разрезе корреспондирующих счетов', NULL),
    ('FB', 'SVAP_QUERY_TYPES', 'PA', 'PA', 'Расчет показателей состояния лицевых счетов', NULL),
    ('FB', 'SVAP_QUERY_TYPES', 'CONS', 'CONS', 'Расчет сводных данных по показателям состояния лицевых счетов', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_PA', 'PA_SVR', 'PA_SVR', 'Анализ состояния лицевого счета СВР', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'FAIP', 'FAIP', 'Сводные показатели ФАИП', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'KMI', 'KMI', 'Сводные показатели КМИ', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'BALBO_GABS', 'BALBO_GABS', 'Сводные показатели по остаткам БА ГРБС/ГАИФ', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_GRBS', 'PA_GRBS', 'Сводные показатели лицевого счета ГРБС', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_GAIF', 'PA_GAIF', 'Сводные показатели лицевого счета ГАИФ', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_PBS', 'PA_PBS', 'Сводные показатели лицевого счета ПБС', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_SVR', 'PA_SVR', 'Сводные показатели лицевого счета СВР', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_AIF', 'PA_AIF', 'Сводные показатели лицевого счета АИФ', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_IPBS', 'PA_IPBS', 'Сводные показатели лицевого счета ИПБС', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'EXP', 'EXP', 'Сводные показатели расходов', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'SRC', 'SRC', 'Сводные показатели источников', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'TMP', 'TMP', 'Сводные показатели временно поступивших средств', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_UKS', 'PA_UKS', 'Сводные показатели УКС', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'PA_PSB', 'PA_PSB', 'Сводные показатели ПСБ', NULL),
    ('FB', 'SVAP_QUERY_REPORT_TYPES_CONS', 'UKS', 'UKS', 'Сводные показатели УКС', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', '=', 'Равно', 'Равно', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'not=', 'Не равно', 'Не равно', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', '<', 'Меньше', 'Меньше', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', '>', 'Больше', 'Больше', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', '<=', 'Меньше либо равно', 'Меньше либо равно', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', '>=', 'Больше либо равно', 'Больше либо равно', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'between', 'Между', 'Отбор в пределах диапазона', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'like', 'Содержит', 'Содержит / похоже', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'not like', 'Не содержит', 'Не содержит', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'empty', 'Пустое значение', 'Проверка на пустое значение', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'not empty', 'Не пустое значение', 'Проверка на непустое значение', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'not exists', 'Отсутствует', 'Аналитический признак отсутствует в записи', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'length', 'Длина', 'Длина строкового аналитического признака', NULL),
    ('FB', 'SVAP_QUERY_OPERATIONS', 'substr', 'Подстрока', 'Подстрока строкового аналитического признака', NULL),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'budgetCode', 'Бюджет', 'Колонка FSG: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'kbk', 'КБК', 'Колонка FSG: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'account', 'Бух счет', 'Колонка FSG: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'ls', 'ЛС', 'Колонка FSG: ЛС', 'ls'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'faip', 'ФАИП', 'Колонка FSG: ФАИП', 'faip'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'oktmo', 'ОКТМО', 'Колонка FSG: ОКТМО', 'oktmo'),
    ('FB', 'SVAP_QUERY_COLUMNS_FSG', 'targetCode', 'Код цели', 'Колонка FSG: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'budgetCode', 'Бюджет', 'Колонка TURN: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'kbk', 'КБК', 'Колонка TURN: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'account', 'Бух счет', 'Колонка TURN: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'pa', 'Лицевой счет', 'Колонка TURN: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'documentId', 'Номер документа', 'Колонка TURN: Номер документа', 'documentId'),
    ('FB', 'SVAP_QUERY_COLUMNS_TURN', 'currencyCode', 'Валюта', 'Колонка TURN: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'budgetCode', 'Бюджет', 'Колонка COR: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'kbk', 'КБК', 'Колонка COR: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'account', 'Бух счет', 'Колонка COR: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'pa', 'Лицевой счет', 'Колонка COR: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'documentId', 'Номер документа', 'Колонка COR: Номер документа', 'documentId'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'tofk', 'ТОФК', 'Колонка COR: ТОФК', 'tofk'),
    ('FB', 'SVAP_QUERY_COLUMNS_COR', 'currencyCode', 'Валюта', 'Колонка COR: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_PA', 'pa', 'Лицевой счет', 'Колонка PA: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_COLUMNS_PA', 'budgetCode', 'Бюджет', 'Колонка PA: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_PA', 'kbk', 'КБК', 'Колонка PA: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_COLUMNS_PA', 'targetCode', 'Код цели', 'Колонка PA: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_PA', 'currencyCode', 'Валюта', 'Колонка PA: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_CONS', 'budgetCode', 'Бюджет', 'Колонка CONS: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_CONS', 'kbk', 'КБК', 'Колонка CONS: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_COLUMNS_CONS', 'targetCode', 'Код цели', 'Колонка CONS: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_CONS', 'currencyCode', 'Валюта', 'Колонка CONS: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_COLUMNS_CONS', 'tofk', 'ТОФК', 'Колонка CONS: ТОФК', 'tofk'),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:136', 'Поступления', 'PA_SVR DATA_136: Поступления', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:290', 'Поступления ВКР', 'PA_SVR DATA_290: Из них поступления ВКР в рублях', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:137', 'Возврат поступлений', 'PA_SVR DATA_137: Возврат поступлений', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:52', 'Поступления с возвратами', 'PA_SVR DATA_52: Поступления с учетом возвратов', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:134', 'Выплаты', 'PA_SVR DATA_134: Выплаты', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:135', 'Восстановление выплат', 'PA_SVR DATA_135: Восстановление выплат', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:53', 'Выплаты с восстановлением', 'PA_SVR DATA_53: Выплаты с учетом восстановлений', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:12', 'Средства без права расходования', 'PA_SVR DATA_12: Средства без права расходования, всего', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:141', 'Средства без права на начало года', 'PA_SVR DATA_141: Средства без права расходования на начало года', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:142', 'Неразрешенные средства текущего периода', 'PA_SVR DATA_142: Средства текущего периода, неразрешенные к использованию', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:31', 'Неразрешенный остаток на начало года', 'PA_SVR DATA_31: Неразрешенный к использованию остаток на начало года', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:42', 'Разрешенный остаток на начало года', 'PA_SVR DATA_42: Разрешенный к использованию остаток на начало года', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:140', 'Остаток контрольный', 'PA_SVR DATA_140: Остаток контрольный', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_PA', 'PA_SVR:3', 'Остаток плановый контрольный', 'PA_SVR DATA_3: Остаток плановый контрольный', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Start_balance_dr', 'Остаток НП Дт руб.', 'RespData:Start_balance_dr: остаток по дебету в рублях на начало периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Start_balance_dr_cur', 'Остаток НП Дт вал.', 'RespData:Start_balance_dr_cur: остаток по дебету в валюте на начало периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Start_balance_cr', 'Остаток НП Кт руб.', 'RespData:Start_balance_cr: остаток по кредиту в рублях на начало периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Start_balance_cr_cur', 'Остаток НП Кт вал.', 'RespData:Start_balance_cr_cur: остаток по кредиту в валюте на начало периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Turnover_dr', 'Оборот Дт руб.', 'RespData:Turnover_dr: оборот по дебету в рублях за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Turnover_dr_cur', 'Оборот Дт вал.', 'RespData:Turnover_dr_cur: оборот по дебету в валюте за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Turnover_cr', 'Оборот Кт руб.', 'RespData:Turnover_cr: оборот по кредиту в рублях за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Turnover_cr_cur', 'Оборот Кт вал.', 'RespData:Turnover_cr_cur: оборот по кредиту в валюте за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'End_balance_dr', 'Остаток КП Дт руб.', 'RespData:End_balance_dr: остаток по дебету в рублях на конец периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'End_balance_dr_cur', 'Остаток КП Дт вал.', 'RespData:End_balance_dr_cur: остаток по дебету в валюте на конец периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'End_balance_cr', 'Остаток КП Кт руб.', 'RespData:End_balance_cr: остаток по кредиту в рублях на конец периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'End_balance_cr_cur', 'Остаток КП Кт вал.', 'RespData:End_balance_cr_cur: остаток по кредиту в валюте на конец периода', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_FSG', 'Currency_code', 'Код валюты', 'RespData:Currency_code: код валюты по ОКВ', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_TURN', 'Turnover_dr', 'Оборот Дт руб.', 'RespData:Turnover_dr: оборот по дебету в рублях за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_TURN', 'Turnover_dr_cur', 'Оборот Дт вал.', 'RespData:Turnover_dr_cur: оборот по дебету в валюте за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_TURN', 'Turnover_cr', 'Оборот Кт руб.', 'RespData:Turnover_cr: оборот по кредиту в рублях за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_TURN', 'Turnover_cr_cur', 'Оборот Кт вал.', 'RespData:Turnover_cr_cur: оборот по кредиту в валюте за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_TURN', 'Currency_code', 'Код валюты', 'RespData:Currency_code: код валюты по ОКВ', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_COR', 'Amnt_val_cur', 'Оборот руб.', 'RespData:Amnt_val_cur: сумма оборота в валюте учета за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_COR', 'Amnt_oper_cur', 'Оборот вал.', 'RespData:Amnt_oper_cur: сумма оборота в валюте операции за период', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_COR', 'CurrencyCode', 'Код валюты', 'RespData:CurrencyCode: код валюты по ОКВ', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_COR', 'RecType', 'Тип записи учета', 'RespData:RecType: тип записи учета', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:136', 'Поступления', 'PA_SVR DATA_136: Поступления', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:137', 'Возврат поступлений', 'PA_SVR DATA_137: Возврат поступлений', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:52', 'Поступления с возвратами', 'PA_SVR DATA_52: Поступления с учетом возвратов', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:134', 'Выплаты', 'PA_SVR DATA_134: Выплаты', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:135', 'Восстановление выплат', 'PA_SVR DATA_135: Восстановление выплат', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_SVR:53', 'Выплаты с восстановлением', 'PA_SVR DATA_53: Выплаты с учетом восстановлений', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'TMP:5', 'Поступления ВКР', 'TMP DATA_5: Из них поступления ВКР в рублях', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'SRC:86', 'Поступления', 'SRC DATA_86: Поступления', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'SRC:87', 'Возврат поступлений', 'SRC DATA_87: Возврат поступлений', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'SRC:85', 'Поступления с возвратами', 'SRC DATA_85: Поступления с учетом возвратов', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'EXP:255', 'Выплаты', 'EXP DATA_255: Выплаты', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'EXP:256', 'Восстановление выплат', 'EXP DATA_256: Восстановление выплат', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_UKS:59', 'Остаток на начало года УКС', 'PA_UKS DATA_59: Остаток на начало года УКС', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_PSB:59', 'Остаток на начало года ПСБ', 'PA_PSB DATA_59: Остаток на начало года ПСБ', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'UKS:9', 'Остаток на начало года УКС', 'UKS DATA_9: Остаток на начало года УКС', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_UKS:140', 'Остаток контрольный УКС', 'PA_UKS DATA_140: Остаток контрольный', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'PA_PSB:140', 'Остаток контрольный ПСБ', 'PA_PSB DATA_140: Остаток контрольный', NULL),
    ('FB', 'SVAP_QUERY_INDICATORS_CONS', 'UKS:10', 'Остаток контрольный УКС', 'UKS DATA_10: Остаток контрольный', NULL),
    ('FB', 'SVAP_QUERY_FILTERS_FSG', 'budgetCode', 'Бюджет', 'Фильтр FSG: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_FSG', 'kbk', 'КБК', 'Фильтр FSG: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_FILTERS_FSG', 'tofk', 'ТОФК', 'Фильтр FSG: ТОФК', 'tofk'),
    ('FB', 'SVAP_QUERY_FILTERS_FSG', 'account', 'Бух счет', 'Фильтр FSG: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_FILTERS_FSG', 'targetCode', 'Код цели', 'Фильтр FSG: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_TURN', 'budgetCode', 'Бюджет', 'Фильтр TURN: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_TURN', 'kbk', 'КБК', 'Фильтр TURN: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_FILTERS_TURN', 'account', 'Бух счет', 'Фильтр TURN: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_FILTERS_TURN', 'pa', 'Лицевой счет', 'Фильтр TURN: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_FILTERS_TURN', 'currencyCode', 'Валюта', 'Фильтр TURN: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'budgetCode', 'Бюджет', 'Фильтр COR: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'kbk', 'КБК', 'Фильтр COR: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'account', 'Бух счет', 'Фильтр COR: Бух счет', 'account'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'pa', 'Лицевой счет', 'Фильтр COR: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'documentId', 'Номер документа', 'Фильтр COR: Номер документа', 'documentId'),
    ('FB', 'SVAP_QUERY_FILTERS_COR', 'currencyCode', 'Валюта', 'Фильтр COR: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_FILTERS_PA', 'pa', 'Лицевой счет', 'Фильтр PA: Лицевой счет', 'pa'),
    ('FB', 'SVAP_QUERY_FILTERS_PA', 'budgetCode', 'Бюджет', 'Фильтр PA: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_PA', 'kbk', 'КБК', 'Фильтр PA: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_FILTERS_PA', 'targetCode', 'Код цели', 'Фильтр PA: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_PA', 'currencyCode', 'Валюта', 'Фильтр PA: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_FILTERS_CONS', 'budgetCode', 'Бюджет', 'Фильтр CONS: Бюджет', 'budgetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_CONS', 'kbk', 'КБК', 'Фильтр CONS: КБК', 'kbk'),
    ('FB', 'SVAP_QUERY_FILTERS_CONS', 'targetCode', 'Код цели', 'Фильтр CONS: Код цели', 'targetCode'),
    ('FB', 'SVAP_QUERY_FILTERS_CONS', 'currencyCode', 'Валюта', 'Фильтр CONS: Валюта', 'currencyCode'),
    ('FB', 'SVAP_QUERY_FILTERS_CONS', 'tofk', 'ТОФК', 'Фильтр CONS: ТОФК', 'tofk')
ON CONFLICT (business, dictionary_code, item_code) DO UPDATE SET
    item_short_name = EXCLUDED.item_short_name,
    item_full_name = EXCLUDED.item_full_name,
    analytical_attribute_code = EXCLUDED.analytical_attribute_code,
    last_updated = CURRENT_TIMESTAMP;
