// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytical-attributes": {
            "get": {
                "description": "RU: Возвращает справочник аналитических признаков, опционально с фильтром по бизнесу. EN: Returns analytical attributes, optionally filtered by business.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionaries"
                ],
                "summary": "RU: Получить аналитические признаки / EN: List analytical attributes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Код бизнеса / EN: Business code",
                        "name": "business",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Список аналитических признаков / EN: Analytical attribute list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AnalyticalAttribute"
                            }
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "RU: Возвращает всю подготовленную конфигурацию, включая еще не примененные изменения. EN: Returns the full pending configuration, including unapplied changes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "RU: Получить текущую подготовленную конфигурацию / EN: Get current pending configuration",
                "responses": {
                    "200": {
                        "description": "RU: Подготовленная конфигурация / EN: Pending configuration",
                        "schema": {
                            "$ref": "#/definitions/config.AppConfig"
                        }
                    }
                }
            },
            "put": {
                "description": "RU: Частично или полностью обновляет подготовленную конфигурацию из JSON-тела без немедленного применения. EN: Partially or fully updates the pending configuration from the JSON body without applying it immediately.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "RU: Обновить подготовленную конфигурацию / EN: Update pending configuration",
                "parameters": [
                    {
                        "description": "RU: Частичный или полный JSON конфигурации / EN: Partial or full configuration JSON",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "204": {
                        "description": "RU: Обновлено, тело ответа отсутствует / EN: Updated, no response body"
                    },
                    "400": {
                        "description": "RU: Некорректное тело запроса / EN: Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/apply": {
            "post": {
                "description": "RU: Сохраняет подготовленную конфигурацию в БД и отправляет уведомление узлам через PostgreSQL NOTIFY. EN: Persists the pending configuration to the database and notifies nodes through PostgreSQL NOTIFY.",
                "tags": [
                    "config"
                ],
                "summary": "RU: Применить подготовленную конфигурацию / EN: Apply pending configuration",
                "responses": {
                    "200": {
                        "description": "RU: Конфигурация применена / EN: Configuration applied"
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/groups": {
            "get": {
                "description": "RU: Возвращает имена доступных групп конфигурации. EN: Returns names of available configuration groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "RU: Получить группы конфигурации / EN: List configuration groups",
                "responses": {
                    "200": {
                        "description": "RU: Группы конфигурации / EN: Configuration groups",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config/groups/{name}": {
            "get": {
                "description": "RU: Возвращает настройки указанной группы: server, svap или retention. EN: Returns settings for the specified group: server, svap, or retention.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "RU: Получить группу конфигурации / EN: Get a configuration group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Имя группы / EN: Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Настройки группы / EN: Group settings",
                        "schema": {}
                    },
                    "404": {
                        "description": "RU: Группа не найдена / EN: Group not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dictionaries": {
            "get": {
                "description": "RU: Возвращает элементы справочников с фильтрами по ФП, коду справочника, строке поиска по краткому/полному наименованию и связанному аналитическому признаку. EN: Returns dictionary items filtered by business, dictionary code, short/full name search query, and linked analytical attribute.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionaries"
                ],
                "summary": "RU: Найти элементы справочников / EN: Search dictionary items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Код функциональной подсистемы / EN: Business code",
                        "name": "business",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RU: Код справочника / EN: Dictionary code",
                        "name": "dictionary_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RU: Поиск по краткому или полному наименованию / EN: Search by short or full name",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RU: Код связанного аналитического признака / EN: Linked analytical attribute code",
                        "name": "analytical_attribute_code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Элементы справочников / EN: Dictionary items",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.DictionaryItem"
                            }
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "RU: Сохраняет элемент справочника. Связь с analytical_attribute_code необязательная. EN: Saves a dictionary item. analytical_attribute_code link is optional.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionaries"
                ],
                "summary": "RU: Создать или обновить элемент справочника / EN: Create or update dictionary item",
                "parameters": [
                    {
                        "description": "RU: Элемент справочника / EN: Dictionary item",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DictionaryItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Элемент сохранен / EN: Dictionary item saved",
                        "schema": {
                            "$ref": "#/definitions/model.DictionaryItem"
                        }
                    },
                    "400": {
                        "description": "RU: Некорректное тело запроса / EN: Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dictionaries/item": {
            "get": {
                "description": "RU: Возвращает один элемент справочника по составному ключу. EN: Returns a single dictionary item by composite key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionaries"
                ],
                "summary": "RU: Получить элемент справочника / EN: Get dictionary item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Код функциональной подсистемы / EN: Business code",
                        "name": "business",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: Код справочника / EN: Dictionary code",
                        "name": "dictionary_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: Код элемента / EN: Item code",
                        "name": "item_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Элемент справочника / EN: Dictionary item",
                        "schema": {
                            "$ref": "#/definitions/model.DictionaryItem"
                        }
                    },
                    "400": {
                        "description": "RU: Не передан обязательный параметр / EN: Required parameter is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Элемент не найден / EN: Item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "RU: Удаляет элемент справочника по составному ключу. EN: Deletes a dictionary item by composite key.",
                "tags": [
                    "dictionaries"
                ],
                "summary": "RU: Удалить элемент справочника / EN: Delete dictionary item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Код функциональной подсистемы / EN: Business code",
                        "name": "business",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: Код справочника / EN: Dictionary code",
                        "name": "dictionary_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: Код элемента / EN: Item code",
                        "name": "item_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "RU: Удалено / EN: Deleted"
                    },
                    "400": {
                        "description": "RU: Не передан обязательный параметр / EN: Required parameter is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Элемент не найден / EN: Item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "RU: Возвращает имя приложения, версию, Git-метаданные и текущее время сервера. EN: Returns application name, version, Git metadata, and current server time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "RU: Получить информацию о приложении / EN: Get application info",
                "responses": {
                    "200": {
                        "description": "RU: Информация о приложении / EN: App info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/queries": {
            "get": {
                "description": "RU: Возвращает список сохраненных запросов пользователя из заголовка X-User-ID. EN: Returns saved queries for the user from the X-User-ID header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Получить сохраненные запросы / EN: List saved queries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Список сохраненных запросов / EN: Saved query list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SavedQuery"
                            }
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "RU: Регистрирует новый шаблон запроса с параметрами фильтрации. Пользователь определяется по заголовку X-User-ID. EN: Registers a new query template with filter parameters. The user is resolved from the X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Создать сохраненный запрос / EN: Create a saved query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "RU: Описание запроса / EN: Query definition",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SavedQuery"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "RU: Запрос создан / EN: Query created",
                        "schema": {
                            "$ref": "#/definitions/model.SavedQuery"
                        }
                    },
                    "400": {
                        "description": "RU: Некорректное тело запроса или видимость / EN: Invalid request body or visibility",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: user_id не совпадает с X-User-ID / EN: user_id does not match X-User-ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queries/{id}": {
            "get": {
                "description": "RU: Возвращает параметры конкретного сохраненного запроса по UUID. EN: Returns details of a saved query by UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Получить сохраненный запрос / EN: Get a saved query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID запроса / EN: Query UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Сохраненный запрос / EN: Saved query",
                        "schema": {
                            "$ref": "#/definitions/model.SavedQuery"
                        }
                    },
                    "400": {
                        "description": "RU: Некорректный UUID запроса / EN: Invalid query UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Запрос принадлежит другому пользователю / EN: Query belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Запрос не найден / EN: Query not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "RU: Удаляет сохраненный запрос и все связанные с ним результаты. EN: Deletes a saved query and all related query results.",
                "tags": [
                    "queries"
                ],
                "summary": "RU: Удалить сохраненный запрос / EN: Delete a saved query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID запроса / EN: Query UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "RU: Удалено, тело ответа отсутствует / EN: Deleted, no response body"
                    },
                    "400": {
                        "description": "RU: Некорректный UUID запроса / EN: Invalid query UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Запрос принадлежит другому пользователю / EN: Query belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Запрос не найден / EN: Query not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queries/{id}/results": {
            "get": {
                "description": "RU: Возвращает историю выполнений для указанного сохраненного запроса. EN: Returns execution history for the specified saved query.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "RU: Получить результаты запроса / EN: List query results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID запроса / EN: Query UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: История результатов / EN: Query result history",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.QueryResult"
                            }
                        }
                    },
                    "400": {
                        "description": "RU: Некорректный UUID запроса / EN: Invalid query UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Запрос принадлежит другому пользователю / EN: Query belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Запрос не найден / EN: Query not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/query/execute": {
            "post": {
                "description": "RU: Запускает запрос к СВАП по сохраненному шаблону. По умолчанию async=true: возвращает задачу со статусом queued, результат появится после завершения в /results. При async=false дожидается выполнения и возвращает результат. EN: Starts a saved query template execution. By default async=true: returns a queued execution job, and the result appears later in /results. With async=false waits for completion and returns the result.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Запустить выполнение сохраненного запроса / EN: Start saved query execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "RU: Параметры выполнения / EN: Execution parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ExecuteQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Выполнение завершено синхронно / EN: Execution completed synchronously",
                        "schema": {
                            "$ref": "#/definitions/api.ExecuteQuerySyncResponse"
                        }
                    },
                    "202": {
                        "description": "RU: Выполнение принято / EN: Execution accepted",
                        "schema": {
                            "$ref": "#/definitions/api.ExecuteQueryAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "RU: Некорректное тело запроса / EN: Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "RU: Запрос принадлежит другому пользователю / EN: Query belongs to another user",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "RU: Запрос не найден / EN: Query not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/query/executions": {
            "get": {
                "description": "RU: Возвращает статусы запусков запросов пользователя из заголовка X-User-ID. EN: Returns query execution statuses for the user from the X-User-ID header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Получить задачи выполнения пользователя / EN: List user query executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Список задач выполнения / EN: Query execution list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.QueryExecution"
                            }
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/query/executions/{id}": {
            "get": {
                "description": "RU: Возвращает статус конкретного запуска запроса. EN: Returns the status of a specific query execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "RU: Получить статус задачи выполнения / EN: Get query execution status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID задачи выполнения / EN: Execution UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Задача выполнения / EN: Query execution",
                        "schema": {
                            "$ref": "#/definitions/model.QueryExecution"
                        }
                    },
                    "400": {
                        "description": "RU: Некорректный UUID задачи / EN: Invalid execution UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Задача принадлежит другому пользователю / EN: Execution belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Задача не найдена / EN: Execution not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/results": {
            "get": {
                "description": "RU: Возвращает все результаты выполнения запросов пользователя из заголовка X-User-ID. EN: Returns all query execution results for the user from the X-User-ID header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "RU: Получить все результаты пользователя / EN: List user query results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Список результатов / EN: Query result list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.QueryResult"
                            }
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/results/{id}": {
            "delete": {
                "description": "RU: Удаляет конкретный результат выполнения запроса и связанные строки данных. EN: Deletes a specific query execution result and its stored data rows.",
                "tags": [
                    "results"
                ],
                "summary": "RU: Удалить результат запроса / EN: Delete a query result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID результата / EN: Result UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "RU: Удалено, тело ответа отсутствует / EN: Deleted, no response body"
                    },
                    "400": {
                        "description": "RU: Некорректный UUID результата / EN: Invalid result UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Результат принадлежит другому пользователю / EN: Result belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Результат не найден / EN: Result not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/results/{id}/data": {
            "get": {
                "description": "RU: Возвращает строки и значения конкретного результата выполнения с поддержкой пагинации. EN: Returns rows and values for a specific execution result with pagination support.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "RU: Получить данные результата / EN: Get query result data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RU: Идентификатор пользователя / EN: User identifier",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RU: UUID результата / EN: Result UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "RU: Количество строк, максимум 1000 / EN: Number of rows to return, max 1000",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "RU: Количество строк для пропуска / EN: Number of rows to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RU: Плоские строки результата / EN: Flat result rows",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "RU: Некорректный UUID, limit или offset / EN: Invalid UUID, limit, or offset",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "RU: Не передан X-User-ID / EN: X-User-ID is missing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "RU: Результат принадлежит другому пользователю / EN: Result belongs to another user",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "RU: Результат не найден / EN: Result not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "RU: Внутренняя ошибка сервера / EN: Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "saved query with id ... was not found"
                }
            }
        },
        "api.ExecuteQueryAcceptedResponse": {
            "type": "object",
            "properties": {
                "execution": {
                    "$ref": "#/definitions/model.QueryExecution"
                },
                "execution_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "query_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ExecuteQueryRequest": {
            "type": "object",
            "properties": {
                "async": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "end_rep_date": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "org_code": {
                    "type": "string"
                },
                "query_id": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start_rep_date": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "api.ExecuteQuerySyncResponse": {
            "type": "object",
            "properties": {
                "execution": {
                    "$ref": "#/definitions/model.QueryExecution"
                },
                "query_id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/model.QueryResult"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "config.AppConfig": {
            "type": "object",
            "properties": {
                "retention": {
                    "$ref": "#/definitions/config.RetentionConfig"
                },
                "server": {
                    "$ref": "#/definitions/config.ServerConfig"
                },
                "svap": {
                    "$ref": "#/definitions/config.SVAPConfig"
                }
            }
        },
        "config.RetentionConfig": {
            "type": "object",
            "properties": {
                "default_ttl": {
                    "description": "Например, \"24h\"",
                    "type": "string"
                },
                "org_ttls": {
                    "description": "Напр. {\"9500\": \"288h\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "role_ttls": {
                    "description": "Напр. {\"admin\": \"72h\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "user_ttls": {
                    "description": "Напр. {\"lobov.vit\": \"144h\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "config.SVAPConfig": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "description": "Ключ - тип запроса (FSG, TURN, PA, CONS и т.д.)",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/config.SVAPEndpoint"
                    }
                }
            }
        },
        "config.SVAPEndpoint": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                }
            }
        },
        "config.ServerConfig": {
            "type": "object",
            "properties": {
                "port": {
                    "type": "string"
                }
            }
        },
        "model.AnalyticalAttribute": {
            "type": "object",
            "properties": {
                "businesses": {
                    "description": "Перечень СВАПОВ (бизнесов), напр. [\"ФБ\", \"ПУД\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "description": "Код ан признака СВАП (напр. BUD_CODE)",
                    "type": "string"
                },
                "in_account": {
                    "description": "Тип признака (в составе счета / не в составе)",
                    "type": "boolean"
                },
                "last_updated": {
                    "type": "string"
                },
                "name": {
                    "description": "Наименование ан признака",
                    "type": "string"
                },
                "use_in_balance": {
                    "description": "Признак участия в расчете балансов",
                    "type": "boolean"
                },
                "validation_type": {
                    "description": "Тип валидации (Service/RegExpression/List)",
                    "type": "string"
                },
                "validation_value": {
                    "description": "Значение для валидации (адрес сервиса/регэксп/JSON списка)",
                    "type": "string"
                }
            }
        },
        "model.DictionaryItem": {
            "type": "object",
            "properties": {
                "analytical_attribute_code": {
                    "type": "string"
                },
                "business": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "dictionary_code": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "short_name": {
                    "type": "string"
                }
            }
        },
        "model.QueryExecution": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_rep_date": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "query_id": {
                    "type": "string"
                },
                "result_id": {
                    "type": "string"
                },
                "start_rep_date": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.QueryResult": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "fetched_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meta": {
                    "description": "Метаинформация для АИ"
                },
                "name": {
                    "type": "string"
                },
                "query_id": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "model.SavedQuery": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "description": "JSON-строка параметров",
                    "type": "string"
                },
                "query_type": {
                    "description": "OPLIST, FSG, TURN, ReportGK, COR, PA, CONS",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "visibility": {
                    "description": "private, organization, public",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API SVAP Query Service / API агрегатора витрин",
	Description:      "RU: API сервиса SVAP Query Service для интеграции со СВАП, управления сохраненными запросами, результатами и динамической конфигурацией. EN: API server for SVAP Query Service, used to integrate with SVAP and manage saved queries, query results, and dynamic configuration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
